import { supabase } from './supabase'
import type { Product } from './types'

/**
 * Full catalog imported from the MarginEdge count sheet.
 * Tuple format: [name, count_unit, bottle_size_ml?]
 * Products with multiple pack sizes are listed once per size so matching
 * can disambiguate.
 */
type CatalogTuple = readonly [name: string, count_unit: string, ml?: number]

const CATALOG_DATA: readonly CatalogTuple[] = [
  // Main / Liquor list
  ['Asahi Super Dry 11.2oz Bottle', 'Bottle (11.2 Fluid Ounces)'],
  ['Asahi Super Dry 11oz Can', 'Can (11 Fluid Ounces)'],
  ['Asahi Super Dry 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Asahi Super Dry Keg(1/4BBL)', 'Keg (1/4BBL) 7.75GAL'],
  ['Balvenie 16yr The French Oak Single Malt Scotch', 'Bottle', 750],
  ['Bar Keep Baked Apple Bitters', 'Bottle', 100],
  ['Bar Mix, Martini', 'Each'],
  ['Belvedere 10 Organic Vodka', 'Bottle', 750],
  ['Bitters, Scrappys Firewater', 'Bottle'],
  ['Black Cherry Juice', 'Bottle'],
  ['Blade and Bow Bourbon', 'Bottle', 750],
  ["Blanton's Special Reserve Single Barrel Kentucky Straight Bourbon Whiskey", 'Bottle', 700],
  ['Blantons Straight From The Barrel', 'Bottle', 700],
  ['Blood Oath Pact No 1 Bourbon', 'Bottle', 750],
  ['Blue Curacao', 'Bottle (Liter)', 1000],
  ['Boba Pops Cocktail Caviar Strawberry', 'Bottle'],
  ["Buchanan's 12yr Deluxe Scotch", 'Bottle', 750],
  ['Bulleit Single Barrel Select Bourbon', 'Bottle', 750],
  ['Bulleit Single Malt Whiskey', 'Bottle', 750],
  ['Calypso Silver Rum', 'Bottle (Liter)', 1000],
  ['Capel Pisco Reservado Liqueur', 'Bottle', 750],
  ['Casa De Reyes Reposado Tequila', 'Bottle', 750],
  ['Casa Dragones Reposado Tequila', 'Bottle', 750],
  ["Case Fat Ice Standard Cube 2''", 'Each'],
  ['Citric Acid', 'Pound'],
  ['Coffee, Bustelo Ground', 'Case'],
  ['Cointreau', 'Bottle (Liter)', 1000],
  ['Collins Spears - Quantity Of 49 Boxed With Dividers 5"x1.25"', 'Each'],
  ['Condesa London Extra Dry Gin', 'Bottle', 750],
  ['Crop Harvest Organic Cucumber Vodka', 'Bottle (Liter)', 1000],
  ['Crown Royal Blackberry Whiskey', 'Bottle', 750],
  ['Cubes - 50 per Box, With Dividers', 'Each'],
  ['Dalmore 21yr Single Malt Scotch', 'Bottle', 750],
  ['DeKuyper Creme De Menthe White', 'Bottle', 750],
  ['DeKuyper Peppermint Schnapps', 'Bottle (Liter)', 1000],
  ['Dolin De Chambery Blanc Vermouth', 'Bottle', 750],
  ['Don Fulano Blanco Suave Tequila', 'Bottle', 750],
  ['Don Fulano Reposado Tequila', 'Bottle', 750],
  ['Dos Hombres Tobala Mezcal', 'Bottle', 750],
  ['Drambuie', 'Bottle (Liter)', 1000],
  ['Dry Well Mountain Vodka', 'Bottle (Liter)', 1000],
  ['Eagle Rare 10yr Bourbon', 'Bottle', 750],
  ['Eagle Rare 17yr Bourbon', 'Bottle', 750],
  ['Effen Cucumber Vodka', 'Bottle (Liter)', 1000],
  ['El Tesoro Yamazaki Mundial Anejo Tequila', 'Bottle', 750],
  ['El Toro Gold Tequila', 'Bottle (Liter)', 1000],
  ['El Toro Silver Tequila', 'Bottle (Liter)', 1000],
  ['Elmer T Lee Single Barrel Sour Mash Bourbon', 'Bottle', 750],
  ['Fee Brothers Fee Foam', 'Bottle (4 Fluid Ounces)'],
  ['Flecha Azul Reposado Tequila', 'Bottle', 750],
  ['Flor de Cana 7yr Rum', 'Bottle', 750],
  ['Fortaleza Reposado Tequila', 'Bottle', 750],
  ['Ghost Hill Organic Vodka', 'Bottle', 750],
  ['Giffard Creme de Cacao White', 'Bottle', 750],
  ['Glendalough Pot Still Irish Whiskey', 'Bottle', 750],
  ['Glenlivet 12yr Scotch', 'Bottle (Liter)', 1000],
  ['Hakata 16yr Sherry Cask Whisky', 'Bottle', 700],
  ['Hakushu 18yr Single Malt Japanese Whiskey', 'Bottle', 750],
  ['Havana Club Anejo Rum', 'Bottle', 750],
  ['Hibiki 12yr Whiskey', 'Bottle', 750],
  ['Hibiki Blossom Harmony 2023 Limited Release Suntory Whisky', 'Bottle', 700],
  ['High Noon Sun Sips Pineapple 12oz Can', 'Can (12 Fluid Ounces)'],
  ['Hogsworth Modern Farm', 'Bottle', 750],
  ['Horse Soldier Premium Straight Bourbon', 'Bottle', 750],
  ['Ice 101 Peppermint Schnapps', 'Bottle', 750],
  ['Ilegal Caribbean Cask Reposado Mezcal', 'Bottle', 750],
  ['InsurifyX1', 'Each'],
  ['Johnnie Walker Blue Ice Chalet Limited Edition Scotch', 'Bottle', 750],
  ['Johnnie Walker Blue King George V Scotch', 'Bottle', 750],
  ['Johnnie Walker Red Scotch', 'Bottle (Liter)', 1000],
  ['Juice, Apple 64oz', 'Bottle'],
  ['Juice, Tangerine', 'Each'],
  ['Junipero Gin', 'Bottle', 750],
  ['Kamiki Intense Wood Whiskey', 'Bottle', 750],
  ['Keg Deposit - At Purchase ($40)', 'Each'],
  ['Keg Deposit - At Return $40', 'Each'],
  ['Komos Anejo Tequila', 'Bottle', 750],
  ['Komos XO Extra Anejo Tequila', 'Bottle', 750],
  ['La Caravedo Puro Quebranta Pisco', 'Bottle', 750],
  ['Lagavulin 16yr Single Malt Scotch', 'Bottle', 750],
  ['Lazy K Bar Bourbon', 'Bottle', 750],
  ['Lillet Rose Aperitif', 'Bottle', 750],
  ['Luxardo Espresso Liqueur', 'Bottle', 750],
  ['Macallan 18yr Double Cask Single Malt Scotch', 'Bottle', 750],
  ['Malic Acid', 'Pound'],
  ['Matcha Powder', 'Ounce'],
  ['Milagro Reposado Tequila', 'Bottle (Liter)', 1000],
  ['Misc Credit - Wine', 'Other'],
  ['Modelo Especial 12oz Can', 'Can (12 Fluid Ounces)'],
  ['Mr Boston Peach Schnapps', 'Bottle (Liter)', 1000],
  ['New Amsterdam Vodka', 'Bottle (Liter)', 1000],
  ['Nikka Miyagikyo 12yr Aromatic Single Malt Whiskey', 'Bottle', 750],
  ['Nikka The Grain Japanese Whiskey', 'Bottle', 750],
  ['Oban 14yr Single Malt Scotch', 'Bottle', 750],
  ['Oka Kura Yuzu Vodka (900ml)', 'Bottle', 900],
  ['Oka Kura Yuzu Vodka (720ml)', 'Bottle', 720],
  ['Onions, Cocktail', 'Jar'],
  ['Oshe Vodka', 'Bottle', 750],
  ['Package Protection- Khalil Lalani', 'Each'],
  ['Patron Cristalino Anejo Tequila', 'Bottle', 750],
  ['Pinnacle Vodka', 'Bottle', 750],
  ['Puree, Guava', 'Bottle'],
  ['Puree, Peach', 'Bottle'],
  ['Rancho Mezcal', 'Bottle', 750],
  ['Raspberries, Frozen', 'Pound'],
  ['Redbreast 12yr Single Pot Still Irish Whiskey', 'Bottle', 750],
  ['Ritual Zero Proof Aperitif', 'Bottle', 750],
  ['Ritual Zero Proof Rum', 'Bottle', 750],
  ['Ritual Zero Proof Whisky', 'Bottle', 750],
  ['Ron Corina Coconut Rum', 'Bottle (Liter)', 1000],
  ['Rumple Minze Peppermint', 'Bottle (Liter)', 1000],
  ['Sapporo 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Shibui Rare Cask 23yr Japanese Whiskey', 'Bottle', 750],
  ['Shibui Single Grain 18yr Whisky', 'Bottle', 750],
  ['Shimauta 5yr Ryukyu Japanese Whisky', 'Bottle', 750],
  ['Shiner Bock 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Silent Pool Gin', 'Bottle', 750],
  ['Sir Davis American Whiskey', 'Bottle', 750],
  ['Soonhari Green Apple Soju', 'Bottle', 375],
  ['Stolichnaya Vodka', 'Bottle (Liter)', 1000],
  ['Syrup, Simple', 'Each'],
  ['Syrup, Watermelon', 'Bottle'],
  ['The Macklowe Straight Rye', 'Bottle', 700],
  ['Thomas H Handy Sazerac Rye', 'Bottle', 750],
  ['Togouchi 12yr Blended Whisky', 'Bottle', 700],
  ['Torada Silver Tequila', 'Bottle (Liter)', 1000],
  ['Truffle, Black', 'Pound'],
  ['Underberg Bitters', 'Bottle', 20],
  ['Weber Ranch 1902 Vodka', 'Bottle (Liter)', 1000],
  ['WhistlePig 6yr PiggyBack Bourbon', 'Bottle (Liter)', 1000],
  ['WhistlePig 6yr PiggyBack Rye', 'Bottle (Liter)', 1000],
  ['WhistlePig Snout to Tail 10yr Bourbon', 'Bottle', 750],
  ['William Larue Weller Bourbon', 'Bottle', 750],
  ['Woodford Reserve Double Oaked Bourbon', 'Bottle', 750],
  ['Yamazaki Umeshu Plum', 'Bottle', 750],
  ['Yamazaki Peated Malt Spanish Oak The Kogei Collection', 'Bottle', 750],

  // Beer Cooler
  ['Coors Light 12oz Bottle', 'Bottle'],
  ['Corona 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Dos Equis Lager 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Fever Tree Ginger Ale 6.8oz', 'Bottle'],
  ['Fever Tree Ginger Beer 200ML', 'Bottle', 200],
  ['Fever Tree Sparkling Lime and Yuzu 200ML Bottle', 'Bottle', 200],
  ['Heineken 0.0 NA 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Juice, Grapefruit 10oz', 'Each'],
  ['Juice, Orange 10oz', 'Each'],
  ['Juice, Pineapple 6oz', 'Each'],
  ['Kingsville', 'Can'],
  ['Kirin Ichiban 12oz Bottle', 'Bottle'],
  ['Kirin Light 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Manhattan Project Half Life IPA 12oz Can', 'Can (12 Fluid Ounces)'],
  ['Michelob Ultra 12oz Bottle', 'Bottle'],
  ['Miller Lite 12oz Bottle', 'Bottle (12 Fluid Ounces)'],
  ['Modelo Especial 12oz Bottle', 'Bottle'],
  ['Red Bull Original 8.4oz Can', 'Can'],
  ['Red Bull Sugar Free 8.4oz Can', 'Can'],
  ['Stella Artois 11oz Bottle', 'Bottle'],

  // Beer - Keg
  ['Asahi Super Dry Keg (1/6BBL)', 'Keg (1/6BBL) 5.16GAL'],
  ['Michelob Ultra Keg (1/6BBL)', 'Keg (1/6BBL) 5.16GAL'],
  ['Sapporo Keg(1/2BBL)', 'Keg (1/2BBL) 15.5GAL'],
  ['The Big German Keg', 'Keg (1/6BBL) 5.16GAL'],

  // Back Bar
  ["Ichiro's Malt Chichibu Malt & Grain Japanese Whisky Limited Edition", 'Bottle', 700],
  ["Ichiro's Special Limited Edition (blue bottle)", 'Bottle'],
  ['Goodnight Vodka', 'Bottle (Liter)', 1000],
  ['Fortaleza Blanco Tequila', 'Bottle', 750],
  ['Fireball Cinnamon Whiskey', 'Bottle (Liter)', 1000],
  ['Feragaia NA Spirit', 'Bottle', 700],
  ['Seedlip Garden NA Spirit', 'Bottle', 750],
  ['Strawberries, Frozen', 'Pound'],
  ['Socorro Reposado Tequila', 'Bottle', 750],
  ['1800 Guachimonton Anejo Tequila', 'Bottle', 750],
  ['1800 Milenio Extra Anejo Tequila', 'Bottle', 750],
  ['818 Reserve Anejo Tequila (375ml)', 'Bottle', 375],
  ['818 Reserve Anejo Tequila (750ml)', 'Bottle', 750],
  ['Absinthe', 'Bottle', 750],
  ['Akashi 5 yr Sherry Cask', 'Bottle', 750],
  ['Akashi Japanese Whiskey', 'Bottle', 750],
  ['Akashi Ume Plum Whiskey', 'Bottle', 750],
  ['Akashi White Oak Single Malt', 'Bottle', 750],
  ['Akashi Wine Cask 5yr', 'Bottle', 750],
  ["Angel's Envy Port Barrel Bourbon", 'Bottle', 750],
  ["Angel's Envy Rye", 'Bottle', 750],
  ['Balvenie 14yr Caribbean Cask Single Malt Scotch', 'Bottle', 750],
  ['Balvenie 16 Year', 'Bottle', 750],
  ['Bardstown Ferrand', 'Bottle', 750],
  ['Basil Hayden Bourbon', 'Bottle', 750],
  ['Basil Hayden Dark Rye', 'Bottle', 750],
  ['Basil Hayden Red Wine Cask', 'Bottle', 750],
  ['Basil Hayden Toast Bourbon', 'Bottle', 750],
  ['Belvedere Organic Vodka (1L)', 'Bottle (Liter)', 1000],
  ['Belvedere Organic Vodka (1.75L)', 'Bottle (1.75 Liters)', 1750],
  ["Blanton's Bourbon", 'Bottle', 750],
  ["Blanton's Gold", 'Bottle', 750],
  ["Blanton's Single Barrel Bourbon", 'Bottle', 750],
  ["Booker's Bourbon", 'Bottle', 750],
  ['Boss Hog X Commander', 'Bottle', 750],
  ['Buffalo Trace Bourbon (1L)', 'Bottle (Liter)', 1000],
  ['Buffalo Trace Bourbon (750ml)', 'Bottle', 750],
  ['Bulleit Bourbon', 'Bottle (Liter)', 1000],
  ['Bulleit Rye', 'Bottle (Liter)', 1000],
  ['Casa Azul Anejo Tequila', 'Bottle', 750],
  ['Casa Azul Organic Reposado Tequila', 'Bottle', 750],
  ['Casa Del Sol Angels Reserve', 'Bottle', 750],
  ['Casa Dragones Anejo 375ml', 'Bottle', 375],
  ['Casa Dragones Anejo Tequila', 'Bottle', 750],
  ['Casa Dragones Blanco Tequila (750ml)', 'Bottle', 750],
  ['Casa Dragones Blanco Tequila (1.5L)', 'Bottle (1.5 Liters)', 1500],
  ['Chambord', 'Bottle', 750],
  ['Chartreuse Green', 'Bottle', 750],
  ['Chivas 25yr Scotch', 'Bottle', 750],
  ['Chivas Regal 18yr Wine Cask Scotch', 'Bottle (Liter)', 1000],
  ['Chopin Vodka', 'Bottle (Liter)', 1000],
  ['Creyente Anejo Cristalino Mezcal', 'Bottle', 750],
  ['Cuervo De La Familia Extra Anejo Tequila', 'Bottle', 750],
  ['Cuervo La Familia Cristalino Tequila', 'Bottle', 750],
  ['Desolas Blanco Mezcal', 'Bottle', 750],
  ["Dewar's Japanese Mizunara Oak Cask Scotch", 'Bottle', 750],
  ['Diamond 151 Rum', 'Bottle (Liter)', 1000],
  ['Dobel 1973', 'Bottle', 750],
  ['DOM Benedictine', 'Bottle (Liter)', 1000],
  ['Don Julio 1942 Tequila (750ml)', 'Bottle', 750],
  ['Don Julio 1942 Tequila (1.5L)', 'Bottle (1.5 Liters)', 1500],
  ['Don Julio 1942 Tequila (1.75L)', 'Bottle (1.75 Liters)', 1750],
  ['Don Julio Anejo Tequila', 'Bottle', 750],
  ['Don Julio Blanco Tequila (1L)', 'Bottle (Liter)', 1000],
  ['Don Julio Blanco Tequila (750ml)', 'Bottle', 750],
  ['Don Julio Blanco Tequila (375ml)', 'Bottle', 375],
  ['Don Julio Reposado Tequila', 'Bottle', 750],
  ['Don Julio Ultima Reserva Extra Anejo Tequila', 'Bottle', 750],
  ['Dos Hombres Joven Mezcal', 'Bottle', 750],
  ['Eagle Rare Bourbon', 'Bottle', 750],
  ['El Tesoro 85th', 'Bottle', 750],
  ['Elijah Craig Small Batch Bourbon', 'Bottle', 750],
  ['Elmer T. Lee Bourbon', 'Bottle', 750],
  ['Empress 1908 Indigo Gin', 'Bottle', 750],
  ['Fernet Branca Liqueur', 'Bottle', 750],
  ['Fireball', 'Bottle', 750],
  ['Fortaleza Blanco', 'Bottle', 750],
  ['Fuji Single Grain (750ml)', 'Bottle', 750],
  ['Fuji Single Grain (700ml)', 'Bottle', 700],
  ['Garrison Brothers Single Barrel Bourbon', 'Bottle', 750],
  ['George T Stagg', 'Bottle', 750],
  ['Glen Fohdry 12yr', 'Bottle', 750],
  ['Glenfiddich 29yr', 'Bottle', 750],
  ['Glenfiddich 30yr Single Malt Scotch', 'Bottle', 750],
  ['Gran Centenario Cristalino Anejo Tequila', 'Bottle', 750],
  ['Gran Centenario Gallardo', 'Bottle', 750],
  ['Gran Centenario Leyenda', 'Bottle', 750],
  ['Gran Gala Triple Orange Liqueur', 'Bottle (Liter)', 1000],
  ['Grand Marnier (1L)', 'Bottle (Liter)', 1000],
  ['Grand Marnier (1.75L)', 'Bottle (1.75 Liters)', 1750],
  ['Hakata 10yr Sherry Cask', 'Bottle', 700],
  ['Hakata 18yr Sherry Cask', 'Bottle', 700],
  ['Haku Suntory Japanese Vodka', 'Bottle', 750],
  ['Hakushu 12yr Single Malt Whiskey', 'Bottle', 750],
  ["Hendrick's Gin", 'Bottle (Liter)', 1000],
  ['Herradura Selección', 'Bottle', 750],
  ['Hibiki 21yr (700ml)', 'Bottle', 700],
  ['Hibiki 21yr (750ml)', 'Bottle', 750],
  ['Hibiki Blossom Harmony 2021 (Khalil)', 'Bottle', 700],
  ["Hibiki Harmony Master's Select Whiskey", 'Bottle', 700],
  ['Hibiki Harmony Whiskey', 'Bottle', 750],
  ['Iwai Blue Label', 'Bottle', 750],
  ['Iwai Chestnut', 'Bottle', 750],
  ['Iwai Tradition', 'Bottle', 750],
  ['Johnnie Walker Black Scotch', 'Bottle (Liter)', 1000],
  ['Johnnie Walker Blue Scotch', 'Bottle', 750],
  ['Johnnie Walker Blue Xordinare', 'Bottle', 750],
  ['Johnnie Walker Green Scotch', 'Bottle', 750],
  ['Johnnie Walker Umami', 'Bottle', 750],
  ['Jose Cuervo Reserva Platino Tequila', 'Bottle', 750],
  ['Kaiyo Mizunara', 'Bottle', 750],
  ['Kamiki', 'Bottle', 750],
  ['Kavalan Fino', 'Bottle', 750],
  ["Kentucky Owl St Patrick's Bourbon", 'Bottle', 750],
  ['Ketel One Botanical Grapefruit Rose Vodka', 'Bottle', 750],
  ['Ketel One Botanical Peach Orange Blossom Vodka', 'Bottle (Liter)', 1000],
  ['Ki No Bi', 'Bottle', 750],
  ['Kikori Whiskey', 'Bottle', 750],
  ['Knob Creek Bourbon', 'Bottle (Liter)', 1000],
  ['Knob Creek Rye', 'Bottle (Liter)', 1000],
  ['Komagatake Tsunuki 2020', 'Bottle', 750],
  ['Komagatake 2022 Green/Black', 'Bottle', 750],
  ['Komos Reposado Rosa Tequila', 'Bottle', 750],
  ['Kura The Whisky', 'Bottle', 750],
  ['Kurayoshi 8yr Sherry Cask', 'Bottle', 700],
  ['Kurayoshi 18yr Single Malt Whiskey', 'Bottle', 700],
  ['Lalo Blanco Tequila (750ml)', 'Bottle', 750],
  ['Lalo Blanco Tequila (1L)', 'Bottle (Liter)', 1000],
  ['Larceny Barrel Proof Bourbon', 'Bottle', 750],
  ['Macallan 12yr Double Cask Scotch', 'Bottle', 750],
  ['Macallan 12yr Sherry Cask Single Malt Scotch 110 Proof', 'Bottle', 750],
  ['Macallan 15yr Double Cask', 'Bottle', 750],
  ['Macallan 18yr Sherry Oak', 'Bottle', 750],
  ['Macallan 25yr Highland Sherry Cask Single Malt Scotch', 'Bottle', 750],
  ['Maestro Dobel 1969', 'Bottle', 750],
  ['Maestro Dobel Cristalino Extra Anejo Tequila', 'Bottle', 750],
  ["Maker's Mark 46 Bourbon", 'Bottle', 750],
  ["Maker's Mark Bourbon", 'Bottle (Liter)', 1000],
  ['Mars Asagi 8yr', 'Bottle', 750],
  ['Mars Cosmo Manzanilla', 'Bottle', 750],
  ['Mars Cosmo Wine Cask', 'Bottle', 750],
  ['Mars Komagatake IPA', 'Bottle', 750],
  ['Mars Tsunuki 2022 Single Malt Whiskey', 'Bottle', 700],
  ['Mars YA', 'Bottle', 750],
  ['Miyabi', 'Bottle', 750],
  ['Monkey 47 Gin', 'Bottle (Liter)', 1000],
  ['Nagahama 8yr', 'Bottle', 750],
  ['Nikka Coffey Gin', 'Bottle', 750],
  ['Nikka Coffey Grain Whiskey', 'Bottle', 750],
  ['Nikka Coffey Malt Whiskey', 'Bottle', 750],
  ['Nikka Coffey Vodka', 'Bottle', 750],
  ['Nikka Days Blended Japanese Whiskey', 'Bottle', 750],
  ['Nikka From The Barrel Whiskey', 'Bottle', 750],
  ['Nikka Taketsuru Pure Malt (Black)', 'Bottle', 750],
  ['Nikka Taketsuru White Label Pure Malt Whiskey', 'Bottle', 750],
  ['Nikka Yoichi Single Malt Whiskey', 'Bottle', 750],
  ['Nikka Yoichi Single Malt 10yr', 'Bottle', 750],
  ["Nolet's Silver Gin", 'Bottle', 750],
  ['Nonino Quintessentia Amaro', 'Bottle', 750],
  ['Old Rip 10yr Van Winkle Bourbon', 'Bottle', 750],
  ['Patron El Cielo Silver Tequila', 'Bottle', 700],
  ['Patron Reposado Tequila', 'Bottle', 750],
  ['Patron Silver Tequila', 'Bottle', 750],
  ['Pinhook Bourbon', 'Bottle', 750],
  ['Ritual Zero Proof Gin', 'Bottle'],
  ['Ron Zacapa Rum', 'Bottle', 750],
  ['Seedlip', 'Bottle', 750],
  ['Seki Sato 21yr Shiki Whiskey', 'Bottle', 750],
  ['Shibui 10yr', 'Bottle', 750],
  ['Shibui 15 yr', 'Bottle', 750],
  ['Shibui 18yr Sherry Cask', 'Bottle', 750],
  ['Shibui 8yr', 'Bottle', 750],
  ['Shibui Grain Select', 'Bottle', 750],
  ['Shibui Pure Malt Japanese Whiskey', 'Bottle', 750],
  ['St George Spiced Pear Liqueur', 'Bottle', 750],
  ['Stolichnaya Elit Vodka', 'Bottle (Liter)', 1000],
  ["Stranahan's Sherry Cask", 'Bottle', 750],
  ['Suntory Plum', 'Bottle', 750],
  ['The Botanist Islay Gin', 'Bottle (Liter)', 1000],
  ['Mars Shinsu The Lucky Cat Whiskey', 'Bottle', 750],
  ['The Macklowe (Black label)', 'Bottle', 750],
  ['The Shin', 'Bottle', 750],
  ['Thomas Handy', 'Bottle', 750],
  ['Togouchi 15yr', 'Bottle', 750],
  ['TX Blended Whiskey', 'Bottle (Liter)', 1000],
  ['Weber Ranch', 'Bottle', 750],
  ['Weller 12yr Aged Bourbon', 'Bottle (Liter)', 1000],
  ['WhistlePig 12 year', 'Bottle', 750],
  ['Woodford Reserve Bourbon', 'Bottle (Liter)', 1000],
  ['Woodford Reserve Rye', 'Bottle (Liter)', 1000],
  ['Yamazaki 12yr Single Malt Japanese Whiskey', 'Bottle', 750],
  ['Yamazaki 18yr Single Malt Japanese Whiskey', 'Bottle', 750],
  ['Yamazaki 2023 Edition', 'Bottle', 750],
  ['Zephyr Black Gin', 'Bottle', 750],

  // Well
  ['Aperol Aperitivo', 'Bottle (Liter)', 1000],
  ['Bacardi Superior Rum', 'Bottle (Liter)', 1000],
  ['Baileys Irish Cream', 'Bottle (Liter)', 1000],
  ['Bombay Sapphire Gin', 'Bottle (Liter)', 1000],
  ['Campari', 'Bottle (Liter)', 1000],
  ['Canton Ginger Liqueur (750ml)', 'Bottle', 750],
  ['Canton Ginger Liqueur (1L)', 'Bottle (Liter)', 1000],
  ['Captain Morgan Spiced Rum', 'Bottle (Liter)', 1000],
  ['Carpano Antica Formula Vermouth', 'Bottle (Liter)', 1000],
  ['Casamigos Blanco Tequila (1L)', 'Bottle (Liter)', 1000],
  ['Casamigos Blanco Tequila (1.75L)', 'Bottle (1.75 Liters)', 1750],
  ['Casamigos Reposado Tequila (1L)', 'Bottle (Liter)', 1000],
  ['Casamigos Reposado Tequila (1.75L)', 'Bottle (1.75 Liters)', 1750],
  ['Chartreuse Yellow', 'Bottle', 750],
  ['Crown Royal Whiskey', 'Bottle (Liter)', 1000],
  ['DeKuyper Sour Apple Schnapps', 'Bottle (Liter)', 1000],
  ['DeKuyper Watermelon Pucker Schnapps', 'Bottle (Liter)', 1000],
  ["Dewar's White Label Scotch", 'Bottle (Liter)', 1000],
  ['Disaronno Amaretto', 'Bottle (Liter)', 1000],
  ['Gekkeikan Sake', 'Bottle', 750],
  ['Giffard Creme De Mure Blackberry Liqueur', 'Bottle', 750],
  ['Giffard Creme de Violette', 'Bottle', 750],
  ['Grenadine', 'Bottle'],
  ['Grey Goose Vodka (1L)', 'Bottle (Liter)', 1000],
  ['Grey Goose Vodka (1.75L)', 'Bottle (1.75 Liters)', 1750],
  ['Hangar 1 Honeycomb Vodka', 'Bottle', 750],
  ['Hangar 1 Mandarin Blossom Vodka', 'Bottle'],
  ['Hennessy VS Cognac', 'Bottle (Liter)', 1000],
  ['Ilegal Joven Mezcal', 'Bottle (Liter)', 1000],
  ['Jack Daniels', 'Bottle (Liter)', 1000],
  ['Jameson Irish Whiskey', 'Bottle (Liter)', 1000],
  ['Jim Beam Bourbon', 'Bottle (Liter)', 1000],
  ['Kahlua', 'Bottle (Liter)', 1000],
  ['Ketel One Botanical Cucumber Mint Vodka', 'Bottle (Liter)', 1000],
  ['Ketel One Vodka', 'Bottle (Liter)', 1000],
  ['Licor 43', 'Bottle (Liter)', 1000],
  ['Licor 43 Chocolate', 'Bottle', 750],
  ['Lillet Blanc', 'Bottle', 750],
  ['Luxardo Maraschino Liqueur', 'Bottle', 750],
  ['Lychee, In Can', 'Can'],
  ['Maestro Dobel Diamante Tequila', 'Bottle', 750],
  ['Maestro Dobel Reposado Tequila', 'Bottle', 750],
  ['Malibu Coconut Rum', 'Bottle (Liter)', 1000],
  ['Martini Dry Vermouth', 'Bottle (Liter)', 1000],
  ['Midori Melon Liqueur', 'Bottle (Liter)', 1000],
  ['Mr Black Coffee Liqueur', 'Bottle', 750],
  ['New Amsterdam Gin (750ml)', 'Bottle', 750],
  ['New Amsterdam Gin (1L)', 'Bottle (Liter)', 1000],
  ['Peach Schnapps', 'Bottle (Liter)', 1000],
  ['Pina Loca Tequila', 'Bottle', 750],
  ['Remy Martin VSOP Cognac', 'Bottle (Liter)', 1000],
  ['Sauza Hacienda Silver Tequila', 'Bottle (Liter)', 1000],
  ['Select Aperitivo (1L)', 'Bottle (Liter)', 1000],
  ['Select Aperitivo (750ml)', 'Bottle', 750],
  ['Soho Lychee Liqueur', 'Bottle', 750],
  ['St Germain Elderflower Liqueur', 'Bottle', 750],
  ['Strega Liqueur', 'Bottle', 700],
  ['Suntory Roku Japanese Gin', 'Bottle', 750],
  ['Suntory Toki Japanese Whiskey', 'Bottle', 750],
  ['Tanqueray Gin', 'Bottle (Liter)', 1000],
  ["Tito's Vodka (1L)", 'Bottle (Liter)', 1000],
  ["Tito's Vodka (750ml)", 'Bottle', 750],
  ['Townes Vodka', 'Bottle (Liter)', 1000],
  ['Triple Sec', 'Bottle (Liter)', 1000],
  ['Yuzuri Yuzu Citrus Liqueur', 'Bottle', 750],
]

export const SEED_CATALOG: Omit<Product, 'id'>[] = CATALOG_DATA.map(
  ([name, count_unit, ml]) => ({
    name,
    count_unit,
    bottle_size_ml: ml ?? null,
    active: true,
  })
)

export async function loadCatalog(): Promise<Product[]> {
  const { data, error } = await (supabase as any)
    .from('products')
    .select('*')
    .eq('active', true)
  if (error) return []
  return (data ?? []) as Product[]
}

/**
 * Seed the catalog on first run, and top it up on later runs if new items
 * were added to SEED_CATALOG. Uses name as the uniqueness key.
 */
export async function ensureCatalogSeeded(): Promise<Product[]> {
  const existing = await loadCatalog()
  const existingNames = new Set(existing.map((p) => p.name.toLowerCase()))
  const missing = SEED_CATALOG.filter(
    (p) => !existingNames.has(p.name.toLowerCase())
  )
  if (missing.length === 0) return existing

  // Insert in chunks so we don't exceed Supabase request limits.
  const chunkSize = 100
  for (let i = 0; i < missing.length; i += chunkSize) {
    const chunk = missing.slice(i, i + chunkSize)
    const { error } = await (supabase as any).from('products').insert(chunk as any)
    if (error) break
  }
  return loadCatalog()
}

/** Simple fuzzy-ish matcher: lowercased substring + token overlap. */
export function matchProduct(
  predicted: string,
  catalog: Product[]
): Product | null {
  if (!predicted || catalog.length === 0) return null
  const p = predicted.toLowerCase()
  let best: { product: Product; score: number } | null = null
  const pTokens = new Set(p.split(/[^a-z0-9]+/).filter(Boolean))
  for (const product of catalog) {
    const name = product.name.toLowerCase()
    let score = 0
    if (name.includes(p) || p.includes(name)) score += 5
    const nameTokens = name.split(/[^a-z0-9]+/).filter(Boolean)
    for (const t of nameTokens) if (pTokens.has(t) && t.length > 2) score += 1
    for (const alias of product.aliases ?? []) {
      if (p.includes(alias.toLowerCase())) score += 3
    }
    if (score > 0 && (!best || score > best.score)) {
      best = { product, score }
    }
  }
  return best && best.score >= 2 ? best.product : null
}
